export const HOME_LISTINGS_REQUEST = 'HOME_LISTINGS_REQUEST';
export const HOME_LISTINGS_SUCCESS = 'HOME_LISTINGS_SUCCESS';
export const HOME_LISTINGS_FAIL = 'HOME_LISTINGS_FAIL';

export const LISTING_ID_REQUEST = 'LISTING_ID_REQUEST';
export const LISTING_ID_SUCCESS = 'LISTING_ID_SUCCESS';
export const LISTING_ID_FAIL = 'LISTING_ID_FAIL';

export const CREATE_LISTING_REQUEST = 'CREATE_LISTING_REQUEST';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_FAIL = 'CREATE_LISTING_FAIL'; 

export const UPLOAD_FILE_GET = 'UPLOAD_FILE_GET';
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL';



